### ISSUE TITLE
微博链接能转成桌面网页版的链接嘛 qwq

### ISSUE THREAD

**Issue by ElgoogUdiab** [LiuZiYang1/Dun-Cookie#1]
插件很好用，star给了👍，孩子很喜欢，敏感肌也能用（x）

但是这毕竟是个PC端的插件，微博的链接点开，看到手机版的微博网页，翻评论翻着翻着就会看到什么手机注册之类的，体验还是有点差

其实只要把目前链接的`m.weibo.cn/status/{mid}`的`status`换成明日方舟（6279793937）/朝陇山（6441489862）的uid，然后把域名换成`weibo.com`就可以了，奈何我不会写JS，不会写 qwq

可能是在 popup.js 的 `x.source == 1` 和 `x.source == 3` 改一下 `x.url`？
或者是 background.js 的 `getCho3` 和 `getWeibo` 里？
这个可能还是作者比较熟一些 qwq

**Comment by KazeLiu** [comment]
好的 有空我去查询api调整

**Comment by phidiaLam** [comment]
1.3.7版本中完成此需求
