### ISSUE TITLE
（Chrome）最近蹲饼在右下角会弹出图片，但是在上方点击插件图标，显示是一片空白，提示错误如下

### ISSUE THREAD

**Issue by kuailezhiju** [LiuZiYang1/Dun-Cookie#3]
1.3.5和1.3.7的都有这个问题

Uncaught TypeError: Cannot read property 'replace' of undefined
上下文
html/popup.html
堆叠追踪
js/popup.js:50 (匿名函数)

**Comment by KazeLiu** [comment]
问题做完已经连夜修复 请在 release 里面下载 Dun-Cookie-1.3.8_Beta 使用 
后续稳定会改为1.3.8正式版
