### ISSUE TITLE
weibo api问题

### ISSUE THREAD

**Issue by felinae98** [LiuZiYang1/Dun-Cookie#4]
https://m.weibo.cn/api/container/getIndex?type=uid&value=6279793937&containerid=1076036279793937&kaze=0.789 这个api，今天没有转发深靛的饼，现在还有什么更加稳定的api吗

**Comment by KazeLiu** [comment]
首先感谢你使用这个蹲饼器
这个api今天被我们发现他在没有登录的情况下会忽略一部分信息
所以我们要走一个登陆流程，初步猜测是要先写cookie在其中
你可以参考[蹲饼器2.0](https://github.com/Enraged-Dun-Cookie-Development-Team/Dun-Cookie-Vue)今天更新的内容
